/**
 * Git hook template generators
 */

import type { AI_PATTERN, Config, HookMode } from '../types.js';
import { DEFAULT_AI_PATTERNS } from '../types.js';
import { toGitPath } from './paths.js';

export interface HookTemplateOptions {
  patterns?: readonly AI_PATTERN[];
}

export interface HookInstallPlanOptions extends HookTemplateOptions {
  config: Config;
  platform?: NodeJS.Platform;
  powerShellCommand?: string;
}

export interface HookArtifact {
  path: string;
  content: string;
  mode?: number;
}

export interface HookInstallPlan {
  mode: HookMode;
  runtime: string;
  files: HookArtifact[];
}

export function sanitizeCommitMessage(
  content: string,
  patterns: readonly AI_PATTERN[] = DEFAULT_AI_PATTERNS,
): string {
  const regexes = patterns.map((pattern) => new RegExp(pattern.pattern, 'i'));
  const lines = content.split(/\r?\n/);
  const filtered = lines.filter((line) => !regexes.some((pattern) => pattern.test(line)));

  while (filtered.length > 0 && /^\s*$/.test(filtered[filtered.length - 1])) {
    filtered.pop();
  }

  return filtered.join('\n');
}

function getPatternLiterals(patterns: readonly AI_PATTERN[]): string {
  return patterns
    .map((pattern) => `new RegExp(${JSON.stringify(pattern.pattern)}, 'i')`)
    .join(',\n    ');
}

function escapePowerShellSingleQuotedString(value: string): string {
  return value.replace(/'/g, "''");
}

function quotePosixShell(value: string): string {
  return `'${value.replace(/'/g, "'\"'\"'")}'`;
}

export function generateNodeHookContent(options: HookTemplateOptions = {}): string {
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;
  const patternLiterals = getPatternLiterals(patterns);

  return `#!/usr/bin/env node
// nococli: Remove AI co-author signatures from commit messages
// Generated by noco (https://github.com/doanbactam/noco)

const fs = require('fs');
const file = process.argv[2];
if (!file) process.exit(0);

const patterns = [
    ${patternLiterals}
];

let content;
try {
  content = fs.readFileSync(file, 'utf8');
} catch {
  process.exit(0);
}

const lines = content.split(/\\r?\\n/);
const filtered = lines.filter(line => !patterns.some(p => p.test(line)));

while (filtered.length > 0 && /^\\s*$/.test(filtered[filtered.length - 1])) {
  filtered.pop();
}

try {
  fs.writeFileSync(file, filtered.join('\\n'));
} catch {
  process.exit(0);
}
`;
}

export function generatePowerShellHookContent(options: HookTemplateOptions = {}): string {
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;
  const serializedPatterns = patterns
    .map((pattern) => `  '${escapePowerShellSingleQuotedString(pattern.pattern)}'`)
    .join('\n');

  return `# nococli: Remove AI co-author signatures from commit messages
# Generated by noco (https://github.com/doanbactam/noco)

param(
  [string]$CommitMessagePath
)

if (-not $CommitMessagePath) {
  exit 0
}

$patterns = @(
${serializedPatterns}
)

try {
  $content = Get-Content -LiteralPath $CommitMessagePath -Raw -ErrorAction Stop
} catch {
  exit 0
}

$lines = $content -split "\\r?\\n"
$filtered = New-Object System.Collections.Generic.List[string]

foreach ($line in $lines) {
  $isAiLine = $false

  foreach ($pattern in $patterns) {
    if ($line -match $pattern) {
      $isAiLine = $true
      break
    }
  }

  if (-not $isAiLine) {
    [void]$filtered.Add($line)
  }
}

while ($filtered.Count -gt 0 -and [string]::IsNullOrWhiteSpace($filtered[$filtered.Count - 1])) {
  $filtered.RemoveAt($filtered.Count - 1)
}

try {
  $encoding = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($CommitMessagePath, [string]::Join("\`n", $filtered), $encoding)
} catch {
  exit 0
}
`;
}

export function generateHookContent(options: HookTemplateOptions = {}): string {
  return generateNodeHookContent(options);
}

export function generateWindowsHookWrapperContent(
  config: Config,
  powerShellCommand: string,
): string {
  const runtime = quotePosixShell(toGitPath(powerShellCommand));
  const powerShellHookFile = quotePosixShell(toGitPath(config.powerShellHookFile));

  return `#!/bin/sh
# nococli: Windows hook wrapper
# Generated by noco (https://github.com/doanbactam/noco)

HOOK_RUNTIME=${runtime}
HOOK_SCRIPT=${powerShellHookFile}

if [ ! -f "$HOOK_SCRIPT" ]; then
  exit 0
fi

"$HOOK_RUNTIME" -NoLogo -NoProfile -ExecutionPolicy Bypass -File "$HOOK_SCRIPT" "$1"
exit $?
`;
}

export function createHookInstallPlan(options: HookInstallPlanOptions): HookInstallPlan {
  const platform = options.platform ?? process.platform;
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;

  if (platform === 'win32') {
    if (!options.powerShellCommand) {
      throw new Error('PowerShell runtime is required for Windows hook installation');
    }

    return {
      mode: 'powershell',
      runtime: options.powerShellCommand,
      files: [
        {
          path: options.config.hookFile,
          content: generateWindowsHookWrapperContent(options.config, options.powerShellCommand),
          mode: 0o755,
        },
        {
          path: options.config.powerShellHookFile,
          content: generatePowerShellHookContent({ patterns }),
          mode: 0o644,
        },
      ],
    };
  }

  return {
    mode: 'node',
    runtime: 'node',
    files: [
      {
        path: options.config.hookFile,
        content: generateNodeHookContent({ patterns }),
        mode: 0o755,
      },
    ],
  };
}

/** Markers that identify a nococli-generated hook file. */
export const NOCO_HOOK_MARKERS = ['Generated by noco', 'nococli:'] as const;

/** File extension used for backing up existing hooks before overwrite. */
export const HOOK_BACKUP_EXT = '.bak';

export function isNococliHook(content: string): boolean {
  return NOCO_HOOK_MARKERS.some((marker) => content.includes(marker));
}

/**
 * Get list of default AI patterns
 */
export function getDefaultPatterns(): readonly AI_PATTERN[] {
  return DEFAULT_AI_PATTERNS;
}

/**
 * Get list of pattern names for display
 */
export function getPatternNames(): string[] {
  return DEFAULT_AI_PATTERNS.map((pattern) => pattern.name);
}
