/**
 * Git hook template generator — produces a cross-platform Node.js hook
 */

import { AI_PATTERN, DEFAULT_AI_PATTERNS } from '../types.js';

export interface HookTemplateOptions {
  patterns?: readonly AI_PATTERN[];
}

/**
 * Generate a standalone Node.js hook that strips AI co-author lines.
 * Uses Node.js instead of sed for cross-platform support (Windows).
 */
export function generateHookContent(options: HookTemplateOptions = {}): string {
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;

  // Convert pattern strings to JS RegExp literal strings for embedding
  const patternLiterals = patterns
    .map((p) => {
      const flags = 'i'; // All patterns are case-insensitive
      return `new RegExp(${JSON.stringify(p.pattern)}, '${flags}')`;
    })
    .join(',\n    ');

  return `#!/usr/bin/env node
// nococli: Remove AI co-author signatures from commit messages
// Generated by noco (https://github.com/doanbactam/noco)

const fs = require('fs');
const file = process.argv[2];
if (!file) process.exit(0);

const patterns = [
    ${patternLiterals}
];

let content;
try {
  content = fs.readFileSync(file, 'utf8');
} catch {
  process.exit(0);
}

const lines = content.split('\\n');
const filtered = lines.filter(line => !patterns.some(p => p.test(line)));

// Strip trailing blank lines
while (filtered.length > 0 && /^\\s*$/.test(filtered[filtered.length - 1])) {
  filtered.pop();
}

fs.writeFileSync(file, filtered.join('\\n'));
`;
}

/**
 * Get list of default AI patterns
 */
export function getDefaultPatterns(): readonly AI_PATTERN[] {
  return DEFAULT_AI_PATTERNS;
}

/**
 * Get list of pattern names for display
 */
export function getPatternNames(): string[] {
  return DEFAULT_AI_PATTERNS.map((p) => p.name);
}
