/**
 * Git hook template generator
 */

import { AI_PATTERN, DEFAULT_AI_PATTERNS } from '../types.js';

export interface HookTemplateOptions {
  patterns?: readonly AI_PATTERN[];
}

/**
 * Generate bash hook content for removing AI co-authors
 */
export function generateHookContent(options: HookTemplateOptions = {}): string {
  const patterns = options.patterns || DEFAULT_AI_PATTERNS;

  // Use -E flag for extended regex (ERE) to support () groups and | alternation
  const sedCommands = patterns
    .map(p => `sed -i -E '/${p.pattern}/d' "$COMMIT_MSG_FILE"`)
    .join('\n');

  return `#!/bin/bash
# git-no-ai-author: Remove AI co-author signatures from commit messages
# Generated by npx git-no-ai-author
# See: https://github.com/yourusername/git-no-ai-author

COMMIT_MSG_FILE=$1

# AI patterns to remove from commit messages
${sedCommands}

# Remove trailing empty lines
sed -i -e :a -e '/^$/{$d;N;ba' -e '}' "$COMMIT_MSG_FILE"
`;
}

/**
 * Get list of default AI patterns
 */
export function getDefaultPatterns(): readonly AI_PATTERN[] {
  return DEFAULT_AI_PATTERNS;
}

/**
 * Get list of pattern names for display
 */
export function getPatternNames(): string[] {
  return DEFAULT_AI_PATTERNS.map(p => p.name);
}
